### ISSUE TITLE
Latest Firmware failing since a month...

### ISSUE THREAD

**Issue by AndreasLueck** [ALD-Models/Prusa-ESP32-Cam-Web-Upload#2]
I love the project and used it for two cams. Now my third is waiting for the next version that is running again... Is there an alternative or will there be hope? Best, Andreas

**Comment by ALD-Models** [comment]
Thanks for your interest. I'll see what I can do.


I'll reply when the update has been pushed. Just been working on other things at the moment.

Jake

**Comment by AndreasLueck** [comment]
It's working again? That's a great surprise!! Thanks for helping so quickly and keep on rocking! Your solution should be featured on Prusa3D...

**Comment by ALD-Models** [comment]
Many thanks. It was just some little changes. I have contacted Prusa but not had any reply :(

If you have any further issues feel free to contact me :)

Jake

**Comment by AndreasLueck** [comment]
Well,

there is one more thing: I tested it and after some minor tweaks (reformatting the SD card to MBR with Fat32 format) and a reset I got a positiv message in the log:
```
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1100
load:0x40078000,len:9232
load:0x40080400,len:6412
entry 0x400806a8
Picture file name: /picture8.jpg
Saved file to path: /picture8.jpg
Going to sleep now
```
But, the process hangs on the "Preparing Installation" task...

Do you have an idea what I'm doing wrong?

Best regards,
Andreas

**Comment by ALD-Models** [comment]
I have been having the same issues with it.

I'll have a look possible tomorrow on why it is happening. The code a few months ago used to work fine until they released individual board firmware which overcomplicated things slightly 😔



Jake

**Comment by AndreasLueck** [comment]
Works like a charm! So cool... Coffee on me and greetings from Germany! Best, Andreas
